spring:
  datasource:
    url: jdbc:postgresql://${AQTS_DATABASE_ADDRESS}:${AQTS_DATABASE_PORT}/${AQTS_DATABASE_NAME}?currentSchema=${AQTS_SCHEMA_NAME}
    username: ${AQTS_SCHEMA_OWNER_USERNAME}
    password: ${AQTS_SCHEMA_OWNER_PASSWORD}
    hikari:
      maximum-pool-size: 1
      connection-test-query: select now()
      auto-commit: false
  jackson:
    serialization:
      WRAP_ROOT_VALUE: true

logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    com.zaxxer: OFF
